# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               A Tagger's Tag
tagline:             'Tagger Swagger got Blink Dagger'
description:         'Special Thanks to Mark Otto for the simplicity provided. '
url:                 http://ralphjsquare.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ralph JJ
  url:               http://weibo.com/xnbx
  email:             jianguo.jiang@outlook.com

# Custom vars
version:             What is version?XD
